### ISSUE TITLE
Feature request - "Magnifying glass"

### ISSUE THREAD

**Issue by mcicogni** [torum/Image-viewer#12]
This program is already very good. Kudos!!

With the addition of a "magnifying glass" feature it would become awesome.

Cheers
Mauro

**Comment by torum** [comment]
Thank you.
I'm getting more and more similar requests lately. Personally, I've never needed "zooming"/"magnifying glass" feature, but I guess I need give it a try... (no promise though :-))

Thank you again.

**Comment by torum** [comment]
I just finished really really basic and experimental zooming feature in version 1.2.17. I uploaded to Microsoft store just now, so it should be available within a few days. I'm not sure this meets your expectation but, hope you try it out. (Press Ctrl key and mouse wheel up and down). 
Thank you again.

**Comment by mcicogni** [comment]
Wow thanks, that's some of the quickest coding I ever saw, from your 
"I'll try something" email to this one, it's 3.5 hours 😲
I'll certainly give it a try as soon as it's available! Do I have to 
update the install manually or should it happen automagically?

Thanks again,
Mauro

--
