### ISSUE TITLE
缩放图片

### ISSUE THREAD

**Issue by sixiansheng** [torum/Image-viewer#13]
你好,你的app很棒,我很喜欢你的app,但是不能缩放图片 令人苦恼

**Comment by torum** [comment]
谢谢 Thank you.
It seems "Magnifying glass" / "Zooming" is important for everyone. I'll try.

**Comment by torum** [comment]
I just finished really really basic and experimental zooming feature in version 1.2.17. I uploaded to Microsoft store just now, so it should be available within a few days. I'm not sure this meets your expectation but, hope you try it out. (Press Ctrl key and mouse wheel up and down).
Thank you again.
