### ISSUE TITLE
Instructions for building on Linux?

### ISSUE THREAD

**Issue by jcoddaire** [torum/Image-viewer#14]
Hi,

Would it be possible to provide instructions for building this on a Linux (Ubuntu, Debian) machine from source? Or a build script?

**Comment by torum** [comment]
Hi! 
Regrettably, I've been little busy lately and have not been able to answer many of the requests/comments here. I promise I will get back to those later.

But, anyway, your question is EASY :-) for me.

You can download Lazarus IDE and FPC(compiler) from here.
https://www.lazarus-ide.org/index.php?page=downloads

Once you downloaded and installed the IDE, just open the project file "ImageViewer.lpr".
When the project is opened, just hit F9 and run.

That's it!
