### ISSUE TITLE
Command Line -s on

### ISSUE THREAD

**Issue by Hiro00000000** [torum/Image-viewer#29]
便利なアプリをありがとうございます

こちらの環境なだけかもしれませんが
コマンドラインの -s on か --inFrame=on をつけると
すぐ閉じちゃって起動できなくなってしまいました
もしバグなら対応よろしくお願いします

**Comment by torum** [comment]
バグ確認しました。報告頂きありがとうございます！なるべく早めに修正して更新版を公開したいと思いますので、ご不便をおかけしますが少々お待ちください。今後ともどうぞよろしくお願いします。

**Comment by torum** [comment]
修正版をリリースしました。アプリストアでは一営業日程度で公開されると思うので、どうぞよろしくお願いいたします。
