### ISSUE TITLE
translate this software

### ISSUE THREAD

**Issue by killtimer920** [torum/Image-viewer#32]
Hello,how do i translate this software into another language?
I don't see a translation button from the software interface that is downloaded by github.

**Comment by torum** [comment]
Hi!
The translation files are located at **src/languages**. They are just text files, so you can just open [ImageViewer.en.po](https://github.com/torum/Image-viewer/blob/master/src/languages/ImageViewer.en.po) and translate and save it as whatever the language. There are currently Japanese translation ImageViewer.ja.po and russian translation, so you can take a look at those for a reference.
Once translation is done, you can send it to me here or create pull request. 
Thank you.

**Comment by killtimer920** [comment]
Ok,thank you!

**Comment by killtimer920** [comment]
Hello, here are two .po files, zh-CN represents Simplified Chinese, zh-Hant represents Traditional Chinese, please check if they are correct, thank you!
Download link:[https://github.com/killtimer920/zh-language-po/tree/main](url)

**Comment by torum** [comment]
Wow, that was quick!
The files look good. Please give me a couple days to apply those translations and get back to you.
Thank you!

**Comment by torum** [comment]
I [released](https://github.com/torum/Image-viewer/releases/tag/v1.4.0.2) the latest version with the translations. Could you test the app in your environment and see if translations appear correctly? Thank you.

**Comment by torum** [comment]
Oh, it just automatically detects OS(Windows)'s language setting. So, if you are using Chinese version of Windows, Image viewer should now display menus in Chinese. If it does not, then there may be a bug in my code...

**Comment by killtimer920** [comment]
Hello, I am indeed using the Chinese version of Windows. Although I tried re-language settings and restarted my computer, the viewer did not display the menu in Chinese.

**Comment by torum** [comment]
OK, thank you for testing. I have some idea why. But first let me try to setup a virtual PC or [Windows Sandbox](https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-overview) in Chinese version and see what is actually going on. Please give me a couple more days. Thanks.

**Comment by torum** [comment]
The proof that I should not write a code when I'm tired. 
It was "zh_Hant" not "zh-Hant"!
Could you test it again with v1.4.2 after I release it?

**Comment by killtimer920** [comment]
yes,I'm glad to test it

**Comment by killtimer920** [comment]
Ok,thank you !
