### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by Esse78** [torum/Image-viewer#7]
Hi, in full screen is it possible to add black color as background color option?

**Comment by torumyax** [comment]
Hello. Black or White color option has already been added. Please check right click menu->background color. Thanks.

________________________________________
差出人: Esse78 <notifications@github.com>
送信日時: 2020年11月15日 13:24
宛先: torum/Image-viewer
CC: Subscribed
件名: [torum/Image-viewer] Sugestion (#7)

Hi, in full screen is it possible to add black color as background color option?

**Comment by Esse78** [comment]
Thanks for the fast replay, but in the windows store version there is no right click menu->background color option

**Comment by torum** [comment]
> there is no right click menu
Perhaps, if you exit full screen mode, you may see the option... The color option can be set in normal mode and full screen uses the same background color as normal mode.

**Comment by Esse78** [comment]
Ahh yes thanks, just to inform you the white and black option are inverted (when the option is white the backgrownd is black and the other way around).
