### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Hoffelhas** [torum/Image-viewer#8]
Hi,

I'm using your wonderful app to view multiple images at the same time, so usually I make them quite small. I've got a very long directory name, however, so I'm not able to see the image name anymore.

Would it be possible to exclude the directory name from the title, and only show the image name?

**Comment by torum** [comment]
Hello. Thank you for your idea. I think it's a good idea. I'll do try that in the next release. Thank you.

**Comment by torum** [comment]
I think it is done (v1.2.13). I decided to shorten the file path depending the window size.  If the window size is small enough, it only shows image's file name. I'll upload the new version to the app store today and it should be available in a few days. Thank you.

**Comment by Hoffelhas** [comment]
Awesome job, thanks a lot for the fast response!

**Comment by Hoffelhas** [comment]
Awesome, thanks a lot!

**Comment by performance-opra** [comment]
Hi, it seems this functionality is no longer active (using v1.2.16), is this correct?

**Comment by torum** [comment]
@performance-opra Thank you for let us know. Yes, currently, resizing window does not update the title format. I may fix it in the future update. Thank you again.
